# 部署 jdk：部署前请先下载 jdk 包解压后放到目录 roles/jdk/files 下
# 并修改 group_vars/all 中的 jdk 对应目录

- hosts: all
  gather_facts: false # 不检测系统信息，有利于加快访问
  serial: 5           # 并发执行，即一次可同时执行 5 个节点，可按实现节点数更改
  become: yes
  become_user: root   # 提权为 root 用户

  roles:
  - jdk
