# 公共系统参数设置
- include_tasks: common.yml

# 系统基础环境环境
- include_tasks: centos.yml
  when: ansible_distribution in [ 'CentOS', 'OracleLinux', 'RedHat']

- include_tasks: debian.yml
  when: ansible_distribution in [ 'Ubuntu', 'Debian']





