- name: 添加 docker 阿里源安装源
  get_url:
    url: "{{ docker_yum_repo }}"
    dest: /etc/yum.repos.d/docker.repo

- name: 刷新 yum 的缓存
  shell: yum clean all && yum makecache fast

- name: 安装 docker-ce
  yum:
    name:
    - docker-ce

- name: Create a directory /etc/docker if it does not exist
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: 添加 docker 国内加速器
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: 配置了 docker，需要运行命令 'systemctl daemon-reload'
  shell: systemctl daemon-reload

- name: 启动 docker 服务
  service:
    name: docker
    state: started
    enabled: yes