#################### 配置java环境 ####################
- name: 第一步：同步 jdk
  synchronize: 
    src: "files/{{ jdk_root_dir }}"
    dest: "{{ dest_dir }}"

- name: 第二步：创建 jdk 的软链接
  file:
    path: "{{ dest_dir }}/jdk"
    state: link
    src: "{{ dest_dir }}/{{ jdk_root_dir }}"
    mode: 0755
    owner: root
    group: root

- name: 第三步：添加变量环境
  lineinfile:
    path: /etc/profile
    line:
      export JAVA_HOME={{ dest_dir }}/jdk
      export PATH=${JAVA_HOME}/bin:$PATH
################### End 配置java环境 ####################
